version: "3.7"

services:

    memory-game-backend:
        build:
            context: backend
            dockerfile: docker/Dockerfile
        restart: unless-stopped
        ports:
            - '3000:3000'

    memory-game-frontend:
        build:
            context: frontend
            dockerfile: docker/Dockerfile
        restart: unless-stopped
        ports:
            - '8080:8080'
